-- ============================================================================
-- Kadam: схема продакшен-базы.
-- Запускать целиком в Supabase → SQL Editor (все блоки подряд, ENTER для деплоя).
-- ============================================================================

-- ---------- Роли ----------
create type public.app_role as enum ('worker', 'employer', 'admin');

-- ---------- Профили (все три роли) ----------
create table if not exists public.profiles (
  id           uuid primary key,               -- = auth.users.id (не FK: сиды без юзера)
  role         public.app_role not null default 'worker',
  name         text not null,
  email        text,
  company      text,                            -- имя компании для работодателя
  initials     text default '',
  avatar_color text default '#6366f1',
  age          int,
  region       text,
  status       text,                            -- unemployed (для воронки)
  months       numeric(4,1),                    -- как давно ищет работу
  desired_role text,                            -- желаемая профессия
  bio          text,
  skills       text[] default '{}',
  years        int,
  education    text,
  languages    text[] default '{}',
  salary_expect int,
  format       text,
  phone        text,
  verified     boolean default true,
  applied      int default 0,
  interview    int default 0,
  currency     text default 'KZT',
  created_at   timestamptz default now()
);

-- ---------- Вакансии ----------
create table if not exists public.jobs (
  id           bigint generated by default as identity primary key,
  employer_id  uuid references public.profiles (id) on delete cascade,
  title        text not null,
  company      text not null,
  region       text not null,
  format       text not null default 'office',   -- office | hybrid | remote
  salary_from  int,
  salary_to    int,
  currency     text default 'KZT',
  type         text default 'full',              -- full | part
  industry     text,
  level        text default 'any',               -- any | junior | middle | senior
  skills       text[] default '{}',
  tags         text[] default '{}',
  demands      text[] default '{}',
  description  text default '',
  status       text default 'active',            -- active | pending | closed
  views        int default 0,
  verified     boolean default false,
  created_at   timestamptz default now()
);
create index if not exists jobs_employer_idx on public.jobs (employer_id);
create index if not exists jobs_status_idx on public.jobs (status);

-- ---------- Отклики / воронка ----------
create table if not exists public.applications (
  id         bigint generated by default as identity primary key,
  job_id     bigint references public.jobs (id) on delete cascade,
  worker_id  uuid references public.profiles (id) on delete cascade,
  stage      text not null default 'saved',      -- saved | applied | interview | offer
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (job_id, worker_id)
);
create index if not exists applications_worker_idx on public.applications (worker_id);

-- ---------- Доступ к таблицам ----------
alter table public.profiles enable row level security;
alter table public.jobs enable row level security;
alter table public.applications enable row level security;

grant usage, select on all sequences in schema public to anon, authenticated, service_role;
grant select, insert, update, delete on public.profiles to anon, authenticated, service_role;
grant select, insert, update, delete on public.jobs to anon, authenticated, service_role;
grant select, insert, update, delete on public.applications to anon, authenticated, service_role;

-- ---------- Хелперы ----------
create or replace function public.is_admin()
returns boolean language sql stable security definer as $$
  select exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin');
$$;

create or replace function public.current_role()
returns text language sql stable as $$
  select role::text from public.profiles where id = auth.uid();
$$;

-- ---------- Политики: profiles ----------
-- Читать профили могут все авторизованные (нужно для матчинга и скрининга).
create policy profiles_select_authed on public.profiles
  for select to authenticated using (true);
-- Редактирует профиль только его владелец (или админ).
create policy profiles_update_own on public.profiles
  for update to authenticated
  using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());
-- Вставка собственного профиля (upsert при сохранении резюме).
create policy profiles_insert_own on public.profiles
  for insert to authenticated
  with check (id = auth.uid());

-- ---------- Политики: jobs ----------
-- Рынок открыт: вакансии читают все (в т.ч. до входа).
create policy jobs_select_public on public.jobs
  for select using (true);
-- Публикует работодатель (свои) или админ. У вас verified=true у новых.
create policy jobs_insert_employer on public.jobs
  for insert to authenticated
  with check (
    (public.current_role() = 'employer' and employer_id = auth.uid())
    or public.is_admin()
  );
create policy jobs_update_owner on public.jobs
  for update to authenticated
  using (
    (public.current_role() = 'employer' and employer_id = auth.uid())
    or public.is_admin()
  );
create policy jobs_delete_owner on public.jobs
  for delete to authenticated
  using (
    (public.current_role() = 'employer' and employer_id = auth.uid())
    or public.is_admin()
  );

-- ---------- Политики: applications ----------
-- Видны самому соискателю, работодателю чью вакансию, админу.
create policy apps_select on public.applications
  for select to authenticated
  using (
    worker_id = auth.uid()
    or public.is_admin()
    or exists (select 1 from public.jobs j where j.id = job_id and j.employer_id = auth.uid())
  );
-- Откликается только соискатель от своего имени.
create policy apps_insert_worker on public.applications
  for insert to authenticated
  with check (
    public.current_role() = 'worker' and worker_id = auth.uid()
  );
-- Статус двигают: сам соискатель, владелец вакансии, админ.
create policy apps_update on public.applications
  for update to authenticated
  using (
    worker_id = auth.uid()
    or public.is_admin()
    or exists (select 1 from public.jobs j where j.id = job_id and j.employer_id = auth.uid())
  );
create policy apps_delete on public.applications
  for delete to authenticated
  using (worker_id = auth.uid() or public.is_admin());

-- ---------- Триггер: профиль создаётся автоматически при регистрации ----------
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  _role text := coalesce(new.raw_user_meta_data ->> 'role', 'worker');
  _name text := coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1));
  _initials text;
begin
  _initials := upper(left(_name, 1))
    || coalesce(upper(left(split_part(_name, ' ', 2), 1)), '');
  insert into public.profiles (id, role, name, email, initials)
  values (new.id, _role::public.app_role, _name, new.email, _initials);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================================
-- СИД-ДАННЫЕ (демо-рынок: 3 работодателя, 8 соискателей, 20 вакансий)
-- ============================================================================

insert into public.profiles (id, role, name, company, region, initials, avatar_color, bio, status, verified)
values
  ('a1111111-1111-4111-8111-111111111111', 'employer', 'ТОО «NurGroup»', 'ТОО «NurGroup»', 'Алматы', 'NG', '#8b5cf6', 'Ритейл и сервис, 240 сотрудников', 'active', true),
  ('b2222222-2222-4222-8222-222222222222', 'employer', 'СтройМетСервис', 'СтройМетСервис', 'Караганда', 'СМ', '#0ea5e9', 'Металлоконструкции и стройпроекты', 'active', true),
  ('c3333333-3333-4333-8333-333333333333', 'employer', 'Демо-партнёры Kadam', 'Демо-партнёры Kadam', 'Алматы', 'ДК', '#10b981', 'Площадка для демо-вакансий', 'active', true);

-- Соискатели (резюме в базе, видны работодателю при скрининге)
insert into public.profiles (id, role, name, initials, avatar_color, age, region, status, months, desired_role, bio, skills, years, education, languages, salary_expect, format, applied, interview, verified)
values
  ('d0000000-0000-4000-8000-000000000001', 'worker', 'Айгерім Серікбол', 'АС', '#6366f1', 28, 'Алматы', 'unemployed', 1.5, 'Бухгалтер / ассистент', 'Выпускница экономического факультета, 2 года вела учёт в семейном бизнесе.', array['бухгалтерия','1c','excel','word'], 2, 'Высшее (экономика)', array['Казахский','Русский'], 350000, 'office', 5, 1, true),
  ('d0000000-0000-4000-8000-000000000002', 'worker', 'Сергей Кан', 'СК', '#0ea5e9', 34, 'Караганда', 'unemployed', 2.5, 'Сварщик / разнорабочий', '6 лет электросварщиком на заводе, разряд 4. Читаю чертежи.', array['сварка','строительство'], 6, 'Средне-специальное', array['Русский'], 450000, 'office', 3, 0, true),
  ('d0000000-0000-4000-8000-000000000003', 'worker', 'Дана Бектасова', 'ДБ', '#ec4899', 23, 'Астана', 'unemployed', 0.8, 'СММ / контент-менеджер', 'Вела Instagram кофейни (12k), снимаю и монтирую shorts.', array['маркетинг','контент','дизайн','интернет'], 2, 'Неоконченное высшее', array['Казахский','Русский'], 280000, 'remote', 8, 2, true),
  ('d0000000-0000-4000-8000-000000000004', 'worker', 'Улан Абдыкадыров', 'УА', '#f59e0b', 41, 'Ош', 'unemployed', 4, 'Водитель / логистика', 'Стаж 20 лет, категории B,C. Ищу работу в городе или на маршрут.', array['вождение'], 20, 'Среднее', array['Кыргызский','Русский'], 40000, 'office', 2, 0, true),
  ('d0000000-0000-4000-8000-000000000005', 'worker', 'Мария Соколова', 'МС', '#10b981', 45, 'Павлодар', 'unemployed', 9, 'Медицинская сестра', 'Опыт медсестры 15 лет, готова вернуться. 1 ставка без подработок.', array['медсестра','коммуникации'], 15, 'Средне-специальное (мед)', array['Русский'], 320000, 'office', 1, 0, true),
  ('d0000000-0000-4000-8000-000000000006', 'worker', 'Нурбек Исаев', 'НИ', '#8b5cf6', 19, 'Бишкек', 'unemployed', 0.6, 'Курьер / официант', 'Студент, первая работа. Готов к физической работе и гибкому графику.', array['общепит','вождение'], 0, 'Студент', array['Кыргызский','Русский'], 20000, 'office', 4, 1, true),
  ('d0000000-0000-4000-8000-000000000007', 'worker', 'Гульмира Туреханова', 'ГТ', '#14b8a6', 31, 'Атырау', 'unemployed', 2.2, 'Продавец / кассир', '5 лет в розничной торговле: касса, выкладка, поставщики.', array['кассы','продажи','коммуникации'], 5, 'Средне-специальное', array['Казахский','Русский'], 300000, 'office', 6, 3, true),
  ('d0000000-0000-4000-8000-000000000008', 'worker', 'Арман Жолдасов', 'АЖ', '#f43f5e', 38, 'Актобе', 'unemployed', 6, 'Оператор линии', '12 лет на производстве: конвейер, упаковка. Без вредных привычек.', array['сборка','интернет'], 12, 'Средне-специальное', array['Казахский','Русский'], 320000, 'office', 2, 0, true);

-- Вакансии (id: 1..20, те же, что в демо)
insert into public.jobs (employer_id, title, company, region, format, salary_from, salary_to, currency, type, industry, level, skills, tags, description, status, views, verified, created_at)
values
  ('c3333333-3333-4333-8333-333333333333', 'Швея на производстве', 'ТехноТекстиль', 'Алматы', 'office', 280000, 380000, 'KZT', 'full', 'Производство', 'any', array['швейное дело','сборка','качества','коммуникации'], array['Обучение на месте','График 5/2','Обед за счёт компании'], 'Пошив спецодежды и постельного белья. Полное обучение на месте.', 'active', 1437, true, now() - interval '18 days'),
  ('a1111111-1111-4111-8111-111111111111', 'Продавец-кассир', 'Супермаркет "Народный"', 'Астана', 'office', 260000, 330000, 'KZT', 'full', 'Торговля', 'any', array['кассы','продажи','коммуникации','интернет'], array['Можно без опыта','Сменный график','Премии'], 'Работа на кассе и в торговом зале. Обучим с нуля за 3 дня.', 'active', 1574, true, now() - interval '17 days'),
  ('b2222222-2222-4222-8222-222222222222', 'Сварщик (полуавтомат/аргон)', 'СтройМетСервис', 'Караганда', 'office', 460000, 580000, 'KZT', 'full', 'Строительство', 'middle', array['сварка','строительство'], array['Вахта / жильё','Официально','Допуски'], 'Сварка металлоконструкций на производственной площадке.', 'active', 1711, true, now() - interval '16 days'),
  ('c3333333-3333-4333-8333-333333333333', 'PHP-разработчик (Junior/Middle)', 'Nomi Digital', 'Алматы', 'hybrid', 600000, 950000, 'KZT', 'full', 'IT и связь', 'middle', array['javascript','python','sql','интернет'], array['Гибрид','ДМС','Рост до Senior'], 'Разработка и поддержка веб-платформ fintech-направления.', 'active', 1848, true, now() - interval '15 days'),
  ('c3333333-3333-4333-8333-333333333333', 'Водитель категории B на такси парк', 'Городское Такси', 'Шымкент', 'office', 320000, 450000, 'KZT', 'full', 'Логистика', 'any', array['вождение'], array['Ежедневные выплаты','Свой или парковый авто'], 'Работа на автомобилях парка или личных. Низкая комиссия.', 'active', 1985, true, now() - interval '14 days'),
  ('c3333333-3333-4333-8333-333333333333', 'Медицинская сестра', 'Городская поликлиника №7', 'Астана', 'office', 300000, 400000, 'KZT', 'full', 'Медицина', 'middle', array['медсестра','коммуникации'], array['Соцпакет','Наставничество'], 'Кабинетный приём, процедурный кабинет. Полный соцпакет.', 'active', 2122, true, now() - interval '13 days'),
  ('c3333333-3333-4333-8333-333333333333', 'Повар на производство', 'Сеть фудзоны "Панда"', 'Бишкек', 'office', 150000, 220000, 'KGS', 'full', 'Питание', 'any', array['кулинария','общепит'], array['Питание за счёт фирмы','График 2/2'], 'Приготовление по технологическим картам. Обучение на рабочем месте.', 'active', 2259, true, now() - interval '12 days'),
  ('a1111111-1111-4111-8111-111111111111', 'Менеджер по продажам', 'Kcell Plus', 'Алматы', 'hybrid', 350000, 700000, 'KZT', 'full', 'Торговля', 'any', array['продажи','коммуникации','телефония','интернет'], array['Оклад + %','Обучение','Карьерный рост'], 'Активные продажи услуг связи корпоративным клиентам.', 'active', 2396, true, now() - interval '11 days'),
  ('c3333333-3333-4333-8333-333333333333', 'Оператор производственной линии', 'Молочная ферма "Айнур"', 'Костанай', 'office', 300000, 400000, 'KZT', 'full', 'Производство', 'any', array['сборка','интернет'], array['Важно внимание','Стабильная смена'], 'Оператор линии розлива и упаковки. Важен аккуратный подход.', 'active', 2533, true, now() - interval '10 days'),
  ('c3333333-3333-4333-8333-333333333333', 'Воспитатель в детский сад', 'ЧУ "Балапан"', 'Павлодар', 'office', 260000, 340000, 'KZT', 'full', 'Образование', 'any', array['работа с детьми','коммуникации'], array['Гибкие графики','Летний отпуск'], 'Работа с группой 3-6 лет. Готовы обучать и переобучать.', 'active', 2670, true, now() - interval '9 days'),
  ('c3333333-3333-4333-8333-333333333333', 'Бухгалтер первичной документации', 'ТОО "Куат Консалтинг"', 'Астана', 'hybrid', 380000, 480000, 'KZT', 'full', 'Услуги', 'middle', array['бухгалтерия','1c','excel'], array['Гибрид','Знание 1С'], 'Проводка первички, авансовые отчёты, сверки. Знание 1С.', 'active', 2807, true, now() - interval '8 days'),
  ('c3333333-3333-4333-8333-333333333333', 'Разнорабочий на стройке (отделка)', 'СтройКомфорт', 'Шымкент', 'office', 250000, 330000, 'KZT', 'full', 'Строительство', 'any', array['строительство'], array['Обучение','Ежедневная оплата'], 'Подсобные работы на отделке: уборка, подача материалов.', 'active', 2944, true, now() - interval '7 days'),
  ('c3333333-3333-4333-8333-333333333333', 'Курьер на автомобиле', 'Доставка "Быстро"', 'Алматы', 'office', 400000, 550000, 'KZT', 'part', 'Логистика', 'any', array['вождение'], array['Гибкий график','Выплаты каждую неделю'], 'Доставка товаров по городу. Гибкий график.', 'active', 3081, true, now() - interval '6 days'),
  ('a1111111-1111-4111-8111-111111111111', 'Ассистент бухгалтера (стажёр)', 'Домбыра Аудит', 'Алматы', 'office', 220000, 280000, 'KZT', 'full', 'Услуги', 'any', array['бухгалтерия','excel','интернет'], array['Для выпускников','Наставник','Карьерный трек'], 'Ведение банка, работа с Excel, подготовка документов для налоговой.', 'active', 3218, true, now() - interval '5 days'),
  ('c3333333-3333-4333-8333-333333333333', 'Дизайнер-верстальщик (удалённо)', 'Издательский дом "Пегас"', 'Бишкек', 'remote', 120000, 180000, 'KGS', 'full', 'IT и связь', 'any', array['дизайн','контент','интернет'], array['Удалённо','Фриланс-формат'], 'Вёрстка книг и корпоративных материалов в InDesign/Figma.', 'active', 3355, true, now() - interval '4 days'),
  ('c3333333-3333-4333-8333-333333333333', 'Официант/бариста (зал и кофе-поинт)', 'Кофейня "Толкын"', 'Астана', 'office', 200000, 320000, 'KZT', 'part', 'Питание', 'any', array['общепит','коммуникации'], array['Чаевые','Обучение бариста','Частичная занятость'], 'Обучение кофе-науке за наш счёт, чаевые на карту.', 'active', 3492, true, now() - interval '3 days'),
  ('c3333333-3333-4333-8333-333333333333', 'Учитель начальных классов', 'Средняя школа гимназия', 'Ош', 'office', 30000, 45000, 'KGS', 'full', 'Образование', 'middle', array['работа с детьми','коммуникации'], array['Классное руководство','Поддержка'], 'Педагогическая деятельность в 1-4 классах.', 'active', 3629, true, now() - interval '2 days'),
  ('b2222222-2222-4222-8222-222222222222', 'Электрогазосварщик', 'МостТрест', 'Актобе', 'office', 420000, 520000, 'KZT', 'full', 'Строительство', 'middle', array['сварка'], array['Вахта 15/15','Разряды 4-6'], 'Монтаж металлоконструкций мостового перехода.', 'active', 1366, true, now() - interval '2 days'),
  ('c3333333-3333-4333-8333-333333333333', 'Администратор колл-центра', 'Салем Сервис', 'Шымкент', 'office', 240000, 300000, 'KZT', 'full', 'Услуги', 'any', array['телефония','коммуникации','интернет','word'], array['Обучение неделя','График 5/2','CRM'], 'Приём и обработка звонков клиентов, ведение базы.', 'active', 1503, true, now() - interval '1 day'),
  ('c3333333-3333-4333-8333-333333333333', 'Специалист по СЕО/контенту', 'Digital Asia Group', 'Астана', 'remote', 300000, 550000, 'KZT', 'full', 'IT и связь', 'middle', array['маркетинг','контент','интернет'], array['Удалённо','Портфолио'], 'Ведение блогов и SEO-оптимизация сайтов.', 'active', 1640, true, now() - interval '12 hours');

-- Отклики для реалистичной воронки
insert into public.applications (job_id, worker_id, stage, created_at)
values
  (4,  'd0000000-0000-4000-8000-000000000003', 'applied',   now() - interval '3 days'),
  (15, 'd0000000-0000-4000-8000-000000000003', 'saved',     now() - interval '2 days'),
  (20, 'd0000000-0000-4000-8000-000000000003', 'interview', now() - interval '1 day'),
  (6,  'd0000000-0000-4000-8000-000000000005', 'applied',   now() - interval '2 days'),
  (12, 'd0000000-0000-4000-8000-000000000005', 'saved',     now() - interval '1 day'),
  (2,  'd0000000-0000-4000-8000-000000000007', 'applied',   now() - interval '4 days'),
  (19, 'd0000000-0000-4000-8000-000000000007', 'interview', now() - interval '1 day');